download_url: https://galaxy.ansible.com/download/community-docker-3.4.8.tar.gz
format_version: 1.0.0
name: docker
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.4.8
version_url: https://galaxy.ansible.com/api/v2/collections/community/docker/versions/3.4.8/
