download_url: https://galaxy.ansible.com/download/debops-debops-3.0.5.tar.gz
format_version: 1.0.0
name: debops
namespace: debops
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.0.5
version_url: https://galaxy.ansible.com/api/v2/collections/debops/debops/versions/3.0.5/
