---
# Configuration for a DebOps project

project:
  default_view: 'debian'

# Define custom paths which can be used to override files and templates in
# Ansible roles or inject tasks via lookup plugins provided with DebOps.
# THe paths are relative to the project root directory.
override_paths:
  files_path: 'ansible/overrides/files'
  tasks_path: 'ansible/overrides/tasks'
  templates_path: 'ansible/overrides/templates'
